### ISSUE TITLE
La aplicacion se rompe cuando se selecciona la institucion. 

### ISSUE THREAD

**Issue by GonzaloSaad** [universy-code/flutter-universy-mobile-client#39]
```
E/flutter ( 8438): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: No institution found with the key FRC
E/flutter ( 8438): #0      AddCareerWidgetState.updateSelectedInstitution (package:universy_mobile_client/com/universy/views/student/career/add-career-widget.dart:166:5)
E/flutter ( 8438): #1      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart)
E/flutter ( 8438): #2      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 8438): #3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8438): #4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 8438): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 8438): #6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 8438): #7      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter ( 8438): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter ( 8438): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 8438): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 8438): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 8438): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 8438): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 8438): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by GonzaloSaad** [comment]
Fix en el branch `gs-user-auth`
